# Generated by Django 4.2.1 on 2023-05-23 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='index',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
