# Generated by Django 4.2.1 on 2023-05-23 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudApp', '0002_alter_index_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='index',
            name='date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
