# Generated by Django 4.2.1 on 2023-06-01 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basic',
            name='content',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='basic',
            name='title',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
