# Generated by Django 4.2 on 2023-05-08 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestbook',
            name='content',
            field=models.TextField(null=True),
        ),
    ]
