# Generated by Django 4.2.1 on 2023-05-23 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='content',
            field=models.TextField(null=True),
        ),
    ]
